#' Subset Alpha Diversity Object
#'
#' This function subsets an alpha diversity object by a specified set of sample IDs.
#'
#' @param alpha.obj Alpha diversity object generated by mStat_calculate_alpha_diversity.
#' @param samIDs A vector of sample IDs to subset by. This can be a logical vector, a numeric vector, or a character vector of sample IDs.
#'
#' @return A list of subsetted alpha diversity indices.
#'
#' @details
#' The function first checks if samIDs is logical or numeric, and if so, converts it to a character vector of sample IDs.
#' Then, it subsets each alpha diversity index in alpha.obj by the sample IDs.
#'
#' @examples
#' \dontrun{
#' # Load required libraries
#' library(MicrobiomeStat)
#' library(vegan)
#'
#' # Create example feature table
#' otu.tab <- matrix(data = rpois(100, 5), nrow = 10, ncol = 10)
#' rownames(otu.tab) <- paste0("Taxon_", 1:10)
#' colnames(otu.tab) <- paste0("Sample_", 1:10)
#'
#' # Calculate alpha diversity indices
#' alpha.obj <- mStat_calculate_alpha_diversity(x = otu.tab, alpha.name = c("shannon", "simpson",
#' "observed_species", "chao1", "ace", "pielou"))
#'
#' # Subset alpha diversity object by sample IDs
#' sample_ids <- sample(colnames(otu.tab), 5)
#' subsetted_alpha.obj <- mStat_subset_alpha(alpha.obj, sample_ids)
#' }
#'
#' @export
mStat_subset_alpha <- function(alpha.obj, samIDs) {
  if (is.null(alpha.obj) || length(alpha.obj) == 0 || is.null(alpha.obj[[1]])) {
    stop("alpha.obj must be a non-empty alpha diversity object.")
  }

  available_samIDs <- rownames(alpha.obj[[1]])
  if (is.logical(samIDs) || is.numeric(samIDs)) {
    samIDs <- available_samIDs[samIDs]
  }

  if (any(is.na(samIDs))) {
    stop("Some requested samIDs are out of range or could not be resolved.")
  }

  samIDs <- unique(as.character(samIDs))
  missing_samIDs <- setdiff(samIDs, available_samIDs)
  if (length(missing_samIDs) != 0) {
    stop(
      "The following samIDs are not present in alpha.obj: ",
      paste(missing_samIDs, collapse = ", ")
    )
  }

  alpha.obj <- lapply(alpha.obj, function(x) {
    if (!is.null(x)) {
      x <- x[samIDs, , drop = FALSE]
    }
    x
  })

  return(alpha.obj)
}
