utils::globalVariables(c(
  "%>%", ".", ":=", "Df", "Estimate", "F.Model", "Feature.ID", "GMPR", "GUniFrac", "MeanSqs", "P.Value",
  "PC", "PC1", "PC2", "Pr(>F)", "R2", "SampleCount", "Statistic", "Std.Error", "SumsOfSqs", "Term",
  "TimePoint", "Variable", "ZicoSeq", "abundance_change", "dplyr::across", "adj.vars", "all_of", "anova", "any_of",
  "dplyr::arrange", "as", "as.dist", "as.formula", "as_tibble", "assay", "assays", "dplyr::bind_cols", "dplyr::bind_rows",
  "biom_data", "dplyr::case_when", "change.after", "cmdscale", "coef", "colData", "colorRampPalette",
  "column_to_rownames", "combined_alpha", "count", "count_t0", "count_ts", "cumulative_mean_value",
  "cumulative_value", "ddply", "desc", "dev.off", "df", "distance", "dplyr::distinct", "drop.tip", "estimate",
  "everything", "experiments", "exprs", "fData", "facet_nested", "facet_nested_wrap", "forcats::fct_relevel",
  "feature", "feature_tab", "full_join", "tidyr::gather", "get_fun_from_pkg", "grid.echo", "group",
  "dplyr::group_by", "dplyr::group_by_at", "group_time", "hcl", "dplyr::if_else", "dplyr::inner_join", "is", "is.rooted",
  "joint_factor", "joint_factor_numeric", "knit_expand", "lag", "dplyr::last", "ldply", "dplyr::lead",
  "dplyr::left_join", "lm", "mean_abundance", "mean_value", "median", "metaMDS", "meta_tab", "method",
  "midpoint", "min_half_value", "model.matrix", "dplyr::mutate", "dplyr::mutate_at", "n", "na.omit",
  "new_count", "next_cumulative_mean_value", "next_cumulative_value", "one_of",
  "otu_table", "p.adjust", "p.value", "pData", "par", "pdf", "pheatmap", "tidyr::pivot_longer",
  "tidyr::pivot_wider", "plot_fun", "prevalence", "prevalence_change", "pt", "dplyr::pull", "quantile",
  "read.csv", "read.nexus", "read.table", "read.tree", "read_biom", "rename", "tidyr::replace_na",
  "rowData", "rowMaxs", "matrixStats::rowSds", "rownames_to_column", "dplyr::rowwise", "rrarefy", "sample_data",
  "sample_metadata", "sd", "tidyr::separate", "setNames", "show_mothur_cutoffs", "tidyr::spread",
  "starts_with", "statistic", "std.error", "strata.var", "subject", "subject.var",
  "subset_data", "dplyr::summarise", "dplyr::summarize", "dplyr::summarize_all", "t.level", "temp", "term",
  "tibble", "time", "time1_mean_abundance", "time1_prevalence",
  "time2_mean_abundance", "time2_prevalence", "total_count", "total_value", "dplyr::ungroup",
  "tidyr::unite", "value", "value_diff", "value_time_1", "value_time_2", "vegdist", "where",
  "x_alternative", "x_end", "x_start", "y_end", "y_start", "zero.handle", "DNAStringSet",
  "calcNormFactors", "scales::percent", "readDNAStringSet", "read_yaml", "scales::rescale", "residuals", "diff_residuals",
  "diff_time", "time_diff", "test_df", "taxa", "diff_value", "Output.Element", "Log2.Fold.Change", "AdjP", "logP","Var1","Freq",
  "avg_abundance", "SequencingDepth", "Group"
))

plot_fun <- function(.call, envir = parent.frame()) {
  if (!inherits(.call, "expression") &&
      !inherits(.call, "formula")    &&
      !inherits(.call, "function")) {

    stop('Argument needs to be of class "expression", "formula", ',
         'or a function that plots to an R graphics device when called, ',
         'but is a ', class(.call))
  }

  if (inherits(.call, "formula")) {
    ## convert to expression
    .call <- parse(text=as.character(.call)[2])
  }

  function() {
    set_par()
    if (inherits(.call, "function"))
      return(.call())
    eval(.call, envir = envir)
  }
}

##' @importFrom graphics par
##' @importFrom grDevices dev.list
##' @importFrom grDevices dev.new
##' @importFrom grDevices dev.off
set_par <- function() {
  if (is.null(dev.list())) {
    dev.new()
    on.exit(dev.off())
  }

  ## https://github.com/wilkelab/cowplot/issues/69#issuecomment-318866413
  par(xpd = NA, # switch off clipping, necessary to always see axis labels
      bg = "transparent", # switch off background to avoid obscuring adjacent plots
      #oma = c(2, 2, 0, 0), # move plot to the right and up
      mgp = c(2, 1, 0) # move axis labels closer to axis
  )
}

##' convert plot to ggplot object
##'
##'
##' @title as.ggplot
##' @param plot base or grid plot, or graphic generated by ggplot, lattice, etc.
##' @param scale scale of the plot to be drawn
##' @param hjust horizontal adjustment
##' @param vjust vertical adjustment
##' @param angle angle to rotate plot
##' @param ... additional parameters passed to as.grob
##' @importFrom ggplot2 ggplot
##' @importFrom ggplot2 aes_
##' @importFrom ggplot2 geom_blank
##' @importFrom ggplot2 annotation_custom
##' @importFrom ggplot2 theme_void
##' @importFrom ggplot2 scale_x_continuous
##' @importFrom ggplot2 scale_y_continuous
##' @return ggplot object
##' @importFrom grid viewport
##' @noRd
##' @examples
##' #library(grid)
##' #as.ggplot(~barplot(1:10))
##' @author Guangchuang Yu
as.ggplot <- function(plot, scale = 1, hjust = 0, vjust = 0, angle = 0, ...) {
  ## plot_expr <- quo_name(enexpr(plot))
  ## if (is.null(plot)) {
  ##     plot <- as.grob(plot_expr)
  ## }

  if (angle == 0) {
    return(as.ggplot_internal(plot = plot,
                              scale = scale,
                              hjust = hjust,
                              vjust = vjust,
                              ...))
  }

  g <- grid2grob(print(as.ggplot_internal(plot, ...),
                       newpage = TRUE,
                       vp = viewport(x = .5 + hjust,
                                     y = .5 + vjust,
                                     angle = angle,
                                     width = scale,
                                     height = scale)
  ))
  as.ggplot(g)
}


as.ggplot_internal <- function(plot, scale = 1, hjust = 0, vjust = 0, ...) {
  ymin <- xmin <- 1 - scale
  xmax <- ymax <- scale

  ggplot(data.frame(x = 0:1, y = 0:1), aes_(x = ~x, y = ~y)) +
    geom_blank() +
    scale_x_continuous(limits = c(0,1), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0,1), expand = c(0, 0)) +
    annotation_custom(as.grob(plot, ...),
                      xmin = xmin + hjust,
                      xmax = xmax + hjust,
                      ymin = ymin + vjust,
                      ymax = ymax + vjust)  +
    theme_void()
}

##' convert a plot to grob object
##'
##'
##' @title as.grob
##' @rdname as-grob
##' @param plot base or grid plot, or graphic object generated by ggplot, lattice, etc.
##' @param ... additional parameter, mostly will be ignored.
##' @return grob object
##' @noRd
##' @examples
##' as.grob(~barplot(1:10))
##' @author Guangchuang Yu
as.grob <- function(plot, ...) {
  UseMethod("as.grob")
}

##' @rdname as-grob
##' @method as.grob aplot
##' @noRd
##' @export
as.grob.aplot <- function(plot, ...) {
  aplotGrob <- utils::getFromNamespace("aplotGrob", "aplot")
  aplotGrob(plot)
}

##' @rdname as-grob
##' @method as.grob bbplot
##' @noRd
as.grob.bbplot <- function(plot, ...) {
  base2grob(~print(plot))
}

##' @rdname as-grob
##' @method as.grob patchwork
##' @noRd
as.grob.patchwork <- function(plot, ...) {
  patchworkGrob <- utils::getFromNamespace("patchworkGrob", "patchwork")
  patchworkGrob(plot)
}


##' @rdname as-grob
##' @method as.grob expression
##' @noRd
as.grob.expression <- function(plot, ...) {
  p <- tryCatch(base2grob(plot, ...),
                error = function(e) NULL)

  if (is.null(p)) {
    p <- grid2grob(plot_fun(plot, ...)())
  }

  return(p)
}

##' @rdname as-grob
##' @method as.grob formula
##' @noRd
as.grob.formula <- as.grob.expression


##' @rdname as-grob
##' @method as.grob function
##' @noRd
as.grob.function <- as.grob.expression

##' @rdname as-grob
##' @importFrom ggplot2 ggplotGrob
##' @method as.grob ggplot
##' @noRd
as.grob.ggplot <- function(plot, ...) {
  ggplotGrob(plot)
}

##' @rdname as-grob
##' @method as.grob meme
##' @noRd
as.grob.meme <- function(plot, ...) {
  memeGrob <- get_fun_from_pkg("meme", "memeGrob")
  memeGrob(plot)
}

##' @rdname as-grob
##' @method as.grob trellis
##' @noRd
as.grob.trellis <- function(plot, ...) {
  grid2grob(print(plot))
}

##' @rdname as-grob
##' @method as.grob eulergram
##' @importFrom grid grid.draw
##' @noRd
as.grob.eulergram <- function(plot, ...) {
  grid2grob(grid.draw(plot))
}

## ComplexHeatmap
##' @rdname as-grob
##' @method as.grob Heatmap
##' @noRd
as.grob.Heatmap <- as.grob.trellis

##' @rdname as-grob
##' @method as.grob upset
##' @noRd
as.grob.upset <- as.grob.trellis

##' @rdname as-grob
##' @method as.grob pheatmap
##' @noRd
as.grob.pheatmap <- function(plot, ...) {
  plot$gtable
}

##' @rdname as-grob
##' @usage NULL
##' @method as.grob magick-image
##' @importFrom grid rasterGrob
##' @noRd
"as.grob.magick-image" <- function(plot, ...) {
  rasterGrob(plot)
}


##' @rdname as-grob
##' @method as.grob grob
##' @noRd
as.grob.grob <- function(plot, ...) {
  plot
}

##' convert base plot to grob object
##'
##'
##' @title base2grob
##' @param x expression or formula of base plot function call, e.g. expression(pie(1:5)) or ~plot(1:10, 1:10);
##' or a function that plots to an R graphics device when called, e.g. function() plot(sqrt)
##' @param envir environment to search variables
##' @return grob object
##' @noRd
##' @examples
##' #base2grob(~plot(rnorm(10)))
##' @author Guangchuang Yu
base2grob <- function(x, envir = parent.frame()) {
  old.par=par(no.readonly=TRUE)
  on.exit(suppressWarnings(par(old.par, no.readonly=TRUE)))

  grid2grob(grid.echo(plot_fun(x, envir = envir)))
}

##' convert grid plot to grob object
##'
##'
##' @title grid2grob
##' @param plot_call plot function call
##' @return grob object
##' @noRd
##' @author Guangchuang Yu
grid2grob <- function(plot_call) {
  grid::grid.grabExpr(plot_call, warn=0)
}


